name: Tests

on: [push, pull_request]

jobs:

  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd
          coverage: none

      - run: php -v
      - run: php -m
      - run: composer -V
      - run: composer install --no-progress
      - run: php vendor/bin/phpunit

  windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd
          coverage: none

      - run: php -v
      - run: php -m
      - run: composer -V
      - run: composer install --no-progress
      - run: php vendor/bin/phpunit

  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: gd
          coverage: none

      - run: composer install --no-progress
      - run: mkdir -p build/logs
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.7.0/php-coveralls.phar
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php php-coveralls.phar --verbose
